//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated at 03/30/2013 13:41:18.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoGridBinderEx.Examples.MVC
{
    using System;
    
    /// <summary>
    /// A static helper class which exposes all strings as const strings which are present in the resource file.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("GlobalResources.tt", "1.0.0.0")]
    public static class GlobalResourceLiterals
    {
        /// <summary>
        /// The string CompanyName
        /// </summary>
        public const string CompanyName = "CompanyName";

        /// <summary>
        /// The string Employee_Company_Required
        /// </summary>
        public const string Employee_Company_Required = "Employee_Company_Required";

        /// <summary>
        /// The string Employee_Email_Invalid
        /// </summary>
        public const string Employee_Email_Invalid = "Employee_Email_Invalid";

        /// <summary>
        /// The string Employee_Email_NotUnique
        /// </summary>
        public const string Employee_Email_NotUnique = "Employee_Email_NotUnique";

        /// <summary>
        /// The string Employee_Email_Required
        /// </summary>
        public const string Employee_Email_Required = "Employee_Email_Required";

        /// <summary>
        /// The string Employee_First_Required
        /// </summary>
        public const string Employee_First_Required = "Employee_First_Required";

        /// <summary>
        /// The string Employee_Fullname_NotUnique
        /// </summary>
        public const string Employee_Fullname_NotUnique = "Employee_Fullname_NotUnique";

        /// <summary>
        /// The string Employee_HireDate_InvalidPast
        /// </summary>
        public const string Employee_HireDate_InvalidPast = "Employee_HireDate_InvalidPast";

        /// <summary>
        /// The string Employee_HireDate_Required
        /// </summary>
        public const string Employee_HireDate_Required = "Employee_HireDate_Required";

        /// <summary>
        /// The string Employee_Last_Required
        /// </summary>
        public const string Employee_Last_Required = "Employee_Last_Required";

        /// <summary>
        /// The string Employee_Number_NotUnique
        /// </summary>
        public const string Employee_Number_NotUnique = "Employee_Number_NotUnique";

        /// <summary>
        /// The string Employee_Number_Required
        /// </summary>
        public const string Employee_Number_Required = "Employee_Number_Required";

        /// <summary>
        /// The string FirstName
        /// </summary>
        public const string FirstName = "FirstName";

        /// <summary>
        /// The string LastName
        /// </summary>
        public const string LastName = "LastName";

        /// <summary>
        /// The string Product_Code_NotUnique
        /// </summary>
        public const string Product_Code_NotUnique = "Product_Code_NotUnique";
    }
}