//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated at 11/22/2012 23:06:46.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoGridBinder.Examples.MVC
{
    using System;
    
    /// <summary>
    /// A static helper class which exposes all strings as const strings which are present in the resource file.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("GlobalResources.tt", "1.0.0.0")]
    public static class GlobalResourceLiterals
    {
        /// <summary>
        /// The string Employee_CompanyId_Required
        /// </summary>
        public const string Employee_CompanyId_Required = "Employee_CompanyId_Required";

        /// <summary>
        /// The string Employee_Fullname_NotUnique
        /// </summary>
        public const string Employee_Fullname_NotUnique = "Employee_Fullname_NotUnique";

        /// <summary>
        /// The string Employee_Number_NotUnique
        /// </summary>
        public const string Employee_Number_NotUnique = "Employee_Number_NotUnique";

        /// <summary>
        /// The string Employee_Number_Required
        /// </summary>
        public const string Employee_Number_Required = "Employee_Number_Required";

        /// <summary>
        /// The string Product_Code_NotUnique
        /// </summary>
        public const string Product_Code_NotUnique = "Product_Code_NotUnique";
    }
}