//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated at 08/29/2014 20:25:21.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoGridBinderEx.Examples.MVC
{
    using System;
    
    /// <summary>
    /// A static helper class which exposes all strings as const strings which are present in the resource file.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("GlobalResources_MVC.tt", "1.0.0.0")]
    public static class GlobalResources_MVCLiterals
    {
    }
}