os: Visual Studio 2017

version: 2.0.0.{build}

configuration:
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe'
- cmd: dotnet-dev-win-x64.latest.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- appveyor-retry dotnet restore src\KendoGridBinder -v Minimal
- appveyor-retry nuget restore examples\KendoGridBinderEx.Examples.Business\KendoGridBinderEx.Examples.Business.csproj -PackagesDirectory packages
- appveyor-retry nuget restore examples\KendoGridBinderEx.Examples.Security\KendoGridBinderEx.Examples.Security.csproj -PackagesDirectory packages
- appveyor-retry nuget restore examples\KendoGridBinderEx.Examples.MVC\KendoGridBinderEx.Examples.MVC.csproj -PackagesDirectory packages

- dotnet build src\KendoGridBinder\KendoGridBinder.csproj -c %CONFIGURATION%
- dotnet build src\KendoGridBinderEx\KendoGridBinderEx.csproj -c %CONFIGURATION%

# - cmd: msbuild examples\KendoGridBinderEx.Examples.Business\KendoGridBinderEx.Examples.Business.csproj /p:Configuration=%CONFIGURATION% /p:Platform=AnyCPU
# - cmd: msbuild examples\KendoGridBinderEx.Examples.Security\KendoGridBinderEx.Examples.Security.csproj /p:Configuration=%CONFIGURATION% /p:Platform=AnyCPU
# - cmd: msbuild examples\KendoGridBinderEx.Examples.MVC\KendoGridBinderEx.Examples.MVC.csproj /p:Configuration=%CONFIGURATION% /p:Platform=AnyCPU

artifacts:
- path: artifacts\**\*.*

cache:
- packages