//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoGridBinderEx.Examples.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources_Business {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources_Business() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KendoGridBinderEx.Examples.Business.GlobalResources_Business", typeof(GlobalResources_Business).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyName.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company Name is required.
        /// </summary>
        public static string Employee_Company_Required {
            get {
                return ResourceManager.GetString("Employee_Company_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email is invalid.
        /// </summary>
        public static string Employee_Email_Invalid {
            get {
                return ResourceManager.GetString("Employee_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email is not unique.
        /// </summary>
        public static string Employee_Email_NotUnique {
            get {
                return ResourceManager.GetString("Employee_Email_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email is required.
        /// </summary>
        public static string Employee_Email_Required {
            get {
                return ResourceManager.GetString("Employee_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FirstName is required.
        /// </summary>
        public static string Employee_First_Required {
            get {
                return ResourceManager.GetString("Employee_First_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fullname &apos;{0}&apos; is not unique.
        /// </summary>
        public static string Employee_Fullname_NotUnique {
            get {
                return ResourceManager.GetString("Employee_Fullname_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Function is required.
        /// </summary>
        public static string Employee_Function_Required {
            get {
                return ResourceManager.GetString("Employee_Function_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HireDate cannot be defined in the past.
        /// </summary>
        public static string Employee_HireDate_InvalidPast {
            get {
                return ResourceManager.GetString("Employee_HireDate_InvalidPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HireDate is required.
        /// </summary>
        public static string Employee_HireDate_Required {
            get {
                return ResourceManager.GetString("Employee_HireDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Manager.
        /// </summary>
        public static string Employee_IsManager {
            get {
                return ResourceManager.GetString("Employee_IsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LastName is required.
        /// </summary>
        public static string Employee_Last_Required {
            get {
                return ResourceManager.GetString("Employee_Last_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number must be between 1000 and 9999.
        /// </summary>
        public static string Employee_Number_Between1000and9999 {
            get {
                return ResourceManager.GetString("Employee_Number_Between1000and9999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number is not unique.
        /// </summary>
        public static string Employee_Number_NotUnique {
            get {
                return ResourceManager.GetString("Employee_Number_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number is required.
        /// </summary>
        public static string Employee_Number_Required {
            get {
                return ResourceManager.GetString("Employee_Number_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SubFunction is required.
        /// </summary>
        public static string Employee_SubFunction_Required {
            get {
                return ResourceManager.GetString("Employee_SubFunction_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Code is not unique.
        /// </summary>
        public static string Product_Code_NotUnique {
            get {
                return ResourceManager.GetString("Product_Code_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubFunction.
        /// </summary>
        public static string SubFunction {
            get {
                return ResourceManager.GetString("SubFunction", resourceCulture);
            }
        }
    }
}
